branches:
  only:
    - master
    - staging
    - experimental

matrix:
  include:
    # devsecops-ci docker
    - language: python
      python: 3.6
      sudo: required
      addons:
        apt:
          packages:
            - docker-ce
      services:
        - docker
      script:
        - make build
        - make test

notifications:
  email: false
