branches:
  only:
    - master
    - experimental

matrix:
  include:
    # devsecops-ci docker
    - language: minimal
      dist: xenial
      services:
        - docker
      script:
        - make build
        - make test
        - make selftest

notifications:
  email: false
